<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-02-04 10:02
=======
# Generated by Django 6.0.1 on 2026-02-03 11:37
>>>>>>> d5cecdf1f115b278e658bde0392cb98c5ed5e38c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
<<<<<<< HEAD
                ('gmail', models.CharField(max_length=100)),
=======
                ('city', models.CharField(max_length=100)),
>>>>>>> d5cecdf1f115b278e658bde0392cb98c5ed5e38c
            ],
        ),
    ]
